apiVersion: apps/v1
kind: service
metadata:
    name:
    labels:
       app: myjavaapp

spec:
  type: Nodeport
  ports:
  - port: 8080
    nodeport: 30001
    protocol: TCP
  selector:
       app: myjavaapp
