apiVersion: v1
kind: ReplicationController
metedata: 
 name: nginx-rc
spec:
  replicas: 3
  selector:
   app: nginx
  template:
   metedata:
    labels:
    app: nginx
   spec:
    containers:
    - name: nginx-container
      image: nginx
      ports:
      - containerport: 80
